### ISSUE TITLE
xbase4j vs. xbasej

### ISSUE THREAD

**Issue by RobWills** [Yasas/xbase4j#1]
Apologies if this is already clarified somewhere but I didn't find it. I am trying to decide on a tool to use to read Foxpro DBF files with java. I am not sure whether the xbase4j uses the xbasej library or is totally separate. Can you please enlighten me? Thanks.

**Comment by Yasas** [comment]
Hi Rob, I apologize for a very late answer. I wrote the **xbase4j** library from scratch because I needed a reliable tool to read DBF files created by different versions of (Visual) FoxPro. I have been using this library for a long time in a production environment, especially for data import and synchronization between DBF and SQL. It is very fast, with a minimum of buffer allocations. Unfortunately, due to commercial projects, I do not have enough time to keep the documentation. However feel free to ask further questions :-)
